project_name: mfa
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main:
    binary: mfa
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -s -w
      - -X github.com/k-saiki/mfa/cmd.version={{.Version}}
      - -X github.com/k-saiki/mfa/cmd.revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - formats: [ 'zip' ]
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
release:
  prerelease: auto
