project_name: mfa
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main:
    binary: mfa
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w
      - -X github.com/k-saiki/mfa/cmd.version={{.Version}}
      - -X github.com/k-saiki/mfa/cmd.revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
release:
  prerelease: auto
